### ISSUE TITLE
Check for Unicode chars in PDF files

### ISSUE THREAD

**Issue by davemcphee** [metachris/pdfx#13]
C:\Users\User\Desktop\python\CouncilAgendaMapper>pdfx --debug agenda.pdf
DEBUG - __init__ - Init with uri: agenda.pdf
Document infos:
- Author = blah
- CreationDate = D:20151106153359-06'00'
Traceback (most recent call last):
  File "C:\Python33\lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python33\lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "C:\Python33\Scripts\pdfx.exe\__main__.py", line 9, in <module>
  File "C:\Python33\lib\site-packages\pdfx\cli.py", line 90, in main
    print("- %s = %s" % (k, parse_str(v).strip("/")))
  File "C:\Python33\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xae' in position 21
: character maps to <undefined>

Not sure what the correct way to handle encoding errors would be, skip the char? 

I usually fix this kind of issue by changing the cmd window encoding, eg.:
cmd> chcp 65001

**Comment by metachris** [comment]
Thanks for reporting! Can you send me the pdf which produces the error?

**Comment by davemcphee** [comment]
Hi Chris,

sure thing, I think it was this:
http://www.austintexas.gov/edims/document.cfm?id=242173

I know nothing about PDF encoding, but I do know about parsing HTML from
that source, and it's all generated in MS Word, so expect a horror show
inside that PDF. Good luck :)

**Comment by metachris** [comment]
Just a note: I've found out that this problem is caused by the Windows console not being able to display unicode characters. I'm going to look into a solution.

* https://wiki.python.org/moin/PrintFails

**Comment by metachris** [comment]
Should work now on the Github version. CLI tries to encode contents to console encoding: https://github.com/metachris/pdfx/blob/b52d3a72b18c7331f025b1d9fec67387fc5dd2d1/pdfx/cli.py#L111
