### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dtolj** [metachris/pdfx#15]
Dependency issue:
Reading http://pypi.python.org/simple/pdfminer2/
Best match: pdfminer2 20151206.macosx-10.10-x86-64
Downloading https://pypi.python.org/packages/e0/55/5e235321d7494772264b577a8569c102b9d9ef867f7239d14d562e89bed9/pdfminer2-20151206.macosx-10.10-x86_64.tar.gz#md5=fa3add6ee50de0132da0f851d12a180b
Processing pdfminer2-20151206.macosx-10.10-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-DYGZND/pdfminer2-20151206.macosx-10.10-x86_64.tar.gz

Why did it download macosx, I am on Linux.

**Comment by marado** [comment]
This will also fail on Mac OS, and is an issue on pdfminer2's package. 
pip install pdfminer2 (or pip install pdfx) will work.

**Comment by marado** [comment]
In any case, there's no reason now to depend on pdfminer2 instead of pdfminer.six ...

**Comment by metachris** [comment]
Solved, using pdfminer.six since v1.4.1. Thanks. Was absent for a long time... kids 😂
