### ISSUE TITLE
Error when running pdf x

### ISSUE THREAD

**Issue by jreme100** [metachris/pdfx#20]
When I attempt to run the program on a PDF I get the following output: 

ImportError: cannot import name settings

Any suggestions as to how I should proceed?

**Comment by khoanguyen8496** [comment]
I have the same problem with pdfx

**Comment by metachris** [comment]
Can you please post the full stack trace?

**Comment by khoanguyen8496** [comment]
I just solved my problem by uninstall the newest version of pdfminer. It seems that pdfminer updated its API so you kinda have to let the pip decide which version to install to fit pdfx.
