### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findall'

### ISSUE THREAD

**Issue by sdwarwick** [metachris/pdfx#27]
complete traceback is:

```
...\lib\site-packages\pdfx\libs\xmp.py", line 50, in meta  
    for desc in self.rdftree.findall(RDF_NS+'Description'):
AttributeError: 'NoneType' object has no attribute 'findall'
```

Have folks seen this error on some pdfs?  

 this is a remote file, addressed through http://

I cannot publish the location of this particular file here, but would appreciate a potential strategy for a solution to this problem!

**Comment by jorgelopezlago** [comment]
I experience the same issue with local pdf files.
I am using Python 2.7.15rc1.

**Comment by stuff-and-nonsense** [comment]
Same issue with local pdf files. Under Python 2.7.16, macOS 10.13.6.

**Comment by metachris** [comment]
Please try again with v1.4.1, and reopen the issue if the issue persists. Thanks 🙏
