### ISSUE TITLE
AttributeError: 'PDFObjRef' object has no attribute 'decode'

### ISSUE THREAD

**Issue by DeepLearner7** [metachris/pdfx#36]
While using pdfx for extraction of url, I got this issue.
![Screenshot from 2019-09-05 10-34-21](https://user-images.githubusercontent.com/27959123/64313682-096d1d00-cfca-11e9-90f8-becd1bd2f3fb.png)

**Comment by metachris** [comment]
Should be fixed now. Please let me know if it still persists with v1.4.1
