### ISSUE TITLE
Thanks a lot, and a question

### ISSUE THREAD

**Issue by MohammedAlrozzi** [metachris/pdfx#42]
Thanks a lot for this great tool. i loved it.
Would you mind helping me in this:
I am translating a very big document (in pdf) and it includes a lot of hyperlinks, which I forgot to attach in the docx of the translation. Now, I have to go through the links in the pdf one by one and open the page, and attach the link to the translated text. I wonder if there is a way to list all the links with their corresponding page. this worked for -c (the broken links) but not when i list the links using -v.
I can send you the pdf file if this helps....

thanks a lot.. very much appreciated.

**Comment by metachris** [comment]
Please attach the PDF. Thanks
